<<<<<<< HEAD
name: Java CI with Maven

on:
  push:
    branches: [ main, Main2 ]
  pull_request:
    branches: [ main, Main2 ]

jobs:
  build:
=======
name: Build and deploy Milestone app to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
   build-and-deploy:
>>>>>>> 74936fda2ada7dc7cc84748016055a37ef166533
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven (skip tests in CI)
<<<<<<< HEAD
        run: mvn -B clean package -DskipTests
=======
        working-directory: Milestones/milestone
        run: mvn -B clean package -DskipTests

      
      - name: Show target folder contents
        working-directory: Milestones/milestone
        run: ls -R target

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Milestoneapp'  
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: 'Milestones/milestone/target/*.jar'
>>>>>>> 74936fda2ada7dc7cc84748016055a37ef166533
